[metadata]
  name = "bitswap-local-speed-test"

[global]
  plan = "bitswap"
  case = "speed-test"
  total_instances = 2
  builder = "docker:go"
  runner = "local:docker"

[global.build_config]
  push_registry=false

[global.run.test_params]
size      = "100MB"
count     = "10"

[[groups]]
  id = "providers"
  instances = { count = 1 }
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"

[[groups]]
  id = "requestors"
  instances = { count = 1 }
  [groups.resources]
    memory = "4096Mi"
    cpu = "1000m"
